INSERT INTO movie (name, pays, category,description,release_date,up_vote,down_vote) VALUES
  ('The Matrix','US','SF/Action','Programmeur anonyme dans un service administratif le jour, 
	Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l''un des pirates les 
	plus recherchés du cyber-espace',parsedatetime('1999-03-31', 'yyyy-MM-dd'),2199,200);
	

INSERT INTO movie (name, pays, category,description,release_date,up_vote,down_vote) VALUES 
('Gladiator','US','Action/Aventure','Le général romain Maximus est le plus fidèle soutien de l''empereur Marc Aurèle,
 qu''il a conduit de victoire en victoire',
 parsedatetime('2000-06-30', 'yyyy-MM-dd'),400,20);
 
 
 INSERT INTO movie (name, pays, category,description,release_date,up_vote,down_vote) VALUES  
 ('Titanic','US','Romance/Drame','En 1997, l''épave du Titanic est l''objet d''une exploration fiévreuse, 
	menée par des chercheurs de trésor en quête d''un diamant bleu qui se trouvait à bord. Frappée par un reportage 
	télévisé, l''une des rescapés du naufrage, âgée de 102 ans, Rose DeWitt, se rend sur place et évoque ses souvenirs',
	parsedatetime('1998-01-07', 'yyyy-MM-dd'),500,28);
 
	
	
	
	
INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2017,'00A','20406','20407','20407','AE',1,'CTN','11',NULL,parsedatetime('2021-10-10 16:42:00','yyyy-MM-dd hh:mm:ss'),'2021-09-22 16:42:00','2021-09-16 12:43:12.688',NULL,'2021-08-30 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','NADOR-MAROC','MOHAMEDIA-MAROC','MOHAMEDIA-MAROC','aa','Emirats Arabes Unis','Exportation',1,1,1,1,'VL005',NULL,'M0001',1,'AF415',NULL,'brouillon','Transport maritime','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2020,'00A','20406','20407','20407','AS',1,'CTN','1',NULL,parsedatetime('2021-10-09 18:45:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 18:45:00','2021-09-16 12:45:57.607',NULL,'2021-10-10 02:00:00','Companie Tunisienne de navigation','1','1','BUREAU 0','NADOR-MAROC','MOHAMEDIA-MAROC','MOHAMEDIA-MAROC','aa','AMERICAN SAMOA','Exportation',1,1,1,1,'11',NULL,'M0001',2,'AR405',NULL,'brouillon','Transport maritime','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2020,'10S','20407','20407','20406','AS',1,'CTN','11',NULL,parsedatetime('2021-09-16 14:46:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 14:46:00','2021-09-16 12:46:41.686',NULL,'2021-09-22 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','MOHAMEDIA-MAROC','MOHAMEDIA-MAROC','NADOR-MAROC','aa','AMERICAN SAMOA','Exportation',1,1,1,1,'11',NULL,'M0003',3,'AR409',NULL,'brouillon','Transport maritime','AUTRES');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2020,'10S','20407','20407','20407','AD',1,'CTN','111',NULL,parsedatetime('2021-09-18 15:18:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 15:18:00','2021-09-16 13:18:45.654',NULL,'2021-09-07 02:00:00','Companie Tunisienne de navigation','111','111','BUREAU 0','MOHAMEDIA-MAROC','MOHAMEDIA-MAROC','MOHAMEDIA-MAROC','aa','ANDORRA','Exportation',1,1,1,1,'11',NULL,'M0004',4,'TN511',NULL,'brouillon','Transport aérien','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2020,'10S','20406','20407','20406','AE',1,'CTN','111',NULL,parsedatetime('2021-10-10 15:20:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 15:20:00','2021-09-16 13:20:56.266',NULL,'2021-09-08 02:00:00','Companie Tunisienne de navigation','11','1','BUREAU 0','NADOR-MAROC','MOHAMEDIA-MAROC','NADOR-MAROC','aa','Emirats Arabes Unis','Exportation',1,1,1,1,'11',NULL,'M0005',5,'SN306',NULL,'brouillon','Transport aérien','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2020,'11S','20407','20406','20407','AS',1,'CTN','111',NULL,parsedatetime('2021-09-19 15:21:00','yyyy-MM-dd hh:mm:ss'),'2021-09-08 15:21:00','2021-09-16 13:21:55.125',NULL,'2021-09-14 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','MOHAMEDIA-MAROC','NADOR-MAROC','MOHAMEDIA-MAROC','aa','AMERICAN SAMOA','Importation',1,1,1,1,'111',NULL,'M0006',6,'SN906',NULL,'brouillon','Transport aérien','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2019,'10S','102','20407','20406','AD',1,'CTN','111',NULL,parsedatetime('2022-01-09 03:25:00','yyyy-MM-dd hh:mm:ss'),'2021-09-16 05:25:00','2021-09-16 17:25:43.539',NULL,'2021-09-15 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','BASTIA-FRANCE','MOHAMEDIA-MAROC','NADOR-MAROC','aa','ANDORRA','Importation',1,1,1,1,'aaa',NULL,'M0077',7,'SN911',NULL,'brouillon','Transport aérien','PORTE CONTENEURS');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2019,'00B','20406','20406','20405','AD',1,'CTN','11',NULL,parsedatetime('2021-09-17 21:59:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 21:59:00','2021-09-16 18:00:19.633',NULL,'2021-09-15 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','NADOR-MAROC','NADOR-MAROC','LAYOUNNE-MAROC','aa','ANDORRA','Exportation',1,11,1,1,'111',NULL,'M0008',8,'AF411',NULL,'brouillon','Transport aérien','AUTRES');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2019,'10S','20405','20406','20406','AS',1,'CTN','111',NULL,parsedatetime('2021-09-16 18:04:05','yyyy-MM-dd hh:mm:ss'),'2021-09-16 18:04:05.832','2021-09-16 18:04:36.955','2021-09-16 18:18:34.828','2021-09-16 18:04:05.832','Companie Tunisienne de navigation','11','11','BUREAU 0','LAYOUNNE-MAROC','NADOR-MAROC','NADOR-MAROC','aa','AMERICAN SAMOA','Exportation',1,1,1,1,'11','0202100002688','M0009',9,'AF432',NULL,'enregistrement','Transport maritime','AUTRES');

INSERT INTO manifeste(annee,bureau_enregistrement,code_lieu_chargement,code_lieu_departmt,code_lieu_destination,code_nationalitemt,code_type_manifeste,companie_transport,conducteur,consignataire,date_arrivee,date_embarquement,date_enreg_entete,date_enregistrement,date_enregistrementmt,description_moyen_transport,jauge_brute,jauge_nette,libelle_bureau_enreg,lieu_chargement,lieu_departmt,lieu_destination,moyen_transport,nationalite,nature_manifeste,nombre_colis,nombre_lignes,nombrett,nombre_unite_de_charge,num_enregmt,numero_enreg,numero_repertoire,numero_seq_rep,numero_vol_voyage,poids_brut_marchandise,statut,type_manifeste,type_navire)
VALUES (2019,'10S','20407','20406','20407','AS',2,'CTN','11',NULL,parsedatetime('2021-10-03 21:02:00','yyyy-MM-dd hh:mm:ss'),'2021-09-15 21:02:00','2021-09-16 19:03:17.728',NULL,'2021-09-13 02:00:00','Companie Tunisienne de navigation','11','11','BUREAU 0','MOHAMEDIA-MAROC','NADOR-MAROC','MOHAMEDIA-MAROC','aa','AMERICAN SAMOA','Importation',1,1,1,1,'111',NULL,'M0010',10,'SN312',NULL,'brouillon','Transport ferroviaire','PORTE CONTENEURS');
 